stages:
  - release

nodejs_docker_job:
  stage: release
  image: docker:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/ui:$CI_COMMIT_TAG renfeid-ui/.
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE/ui:$CI_COMMIT_TAG

java_docker_job:
  stage: release
  image: docker:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/service:$CI_COMMIT_TAG renfeid-service/.
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE/service:$CI_COMMIT_TAG
