logging:
  level:
    net.renfei: DEBUG
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://local.renfei.net:3306/renfeid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&useMysqlMetadata=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      # 其他配置在：net.renfei.common.core.config.PrimaryDataSourceConfig
      stat-view-servlet:
        login-username: admin
        login-password: admin
    discuz:
      url: jdbc:mariadb://local.renfei.net:3306/discuz?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password: password
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  mail:
    host: smtp.163.com
    port: 465
    username: unittesting@163.com
    password: LIHHGXNJTROOXETM
    protocol: smtp
    default-encoding: UTF-8
    reply-to: unittesting@163.com
    properties:
      mail.smtp.localhost: renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    jndi-name: mail/Session
  elasticsearch:
    uris: http://local.renfei.net:9200
    username: elastic
    password: elastic
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

# 自定义配置
system:
  active: dev
  version: "@project.version@"
  buildTime: "@buildtimestamp@"
  siteName: 任霏的博客
  siteDomainName: https://www.renfei.net
  staticDomainName: https://cdn.renfei.net
  # 超管用户名
  superTubeUserName: renfei
  # 是否启用超管，涉密系统不允许出现超管账号
  enableSuperTubeUser: true
  # 系统管理员 角色名（需要与数据库中一致）
  systemSuperRoleName: 系统管理员
  # 安全保密管理员 角色名（需要与数据库中一致）
  securitySuperRoleName: 安全保密管理员
  # 安全审计管理员 角色名（需要与数据库中一致）
  auditSuperRoleName: 安全审计管理员
  # 是否启用缓存
  enableCache: true
  # 是否启用内容发布审核流程机制
  enablePostAuditing: false
  # 是否允许跨域请求
  allowCORS: true
  # 系统允许的最大密级
  maxSecretLevel: UNCLASSIFIED
  # 是否启用注册功能
  enableSignUp: true
  # 是否启用内容审核（阿里云内容安全）
  enableAudit: true
  # Token 是否与 IP 做强绑定
  bindingIp: false
  # 是否记录响应内容（开启后日志表将变大）
  recordResponse: false
  # IP2Location 数据库 Bin 文件请到此处下载：https://github.com/renfei/ip2location
  ip2LocationBinFile: classpath:/IP2LOCATION-LITE-DB11/IP2LOCATION-LITE-DB11.IPV6.BIN
  # 忽略鉴权的地址
  authIgnore:
    - /_/api/test
  # 分词主词典文件
  mainDict: /Users/renfei/Downloads/sogou.txt
  totpSecret: dH6xS3rG7eS6oS3bK9aN4iW8bR2vU9nV
  jwt:
    secret: zL4pC7mP4vH4nY2cK1kE6lC3bJ0yC5wI4kB0kZ2wK4tW3nQ9vP1hO6vZ5jA7wP7ulN6vY3mQ7uI5wU5sE6yP0hP6pK0tF5tT1oO0nO2mL4nO8uP3kJ3rV3iJ4aD5iB5h
    issuer: RENFEI.NET
    expiration: 28800000
  uCenter:
    enable: false
    api: https://bbs.renfei.net/uc_server
    key: <key>
    appId: 3
    connect:
  aws:
    region: ap-east-1
    bucketName: s3-bucket-dev-test
  aliyun:
    accessKeyId: accessKeyId
    accessKeySecret: accessKeySecret
    oss:
      regionId: cn-beijing
      endpoint: http://oss-cn-hangzhou.aliyuncs.com
      bucketName: renfei
    green:
      regionId: cn-beijing
    sms:
      endpoint: dysmsapi.aliyuncs.com
      signName: 任霏博客
      templateCode: SMS_205876320
  leaf:
    port: 2181
    zk: localhost
  # 访问频次限制
  accessLimit:
    # 是否启用访问频次限制
    enable: true
    # 是否启用 WAF 防火墙联动（启用后超过频次将拉黑IP）
    blacklistEnable: true
    # 全局限速包括页面与接口所有
    globalRate: 250
    # 开放 API 限速（当它大于全局时取全局限速，全局限速优先级更高）
    apiRate: 250
    # WAF 联动拉黑的阈值
    blacklistRate: 500
    # 数据采集周期（秒）
    time: 300
    # 通知邮件（联动 WAF 拉黑 IP 后有邮件通知）
    noticeEmail: i@renfei.net
  cloudflare:
    accountId: dd
    token: dd
  weChat:
    mp:
      appId: wx0aeac235b86963c1
      appSecret: a2443ee4b6d60e202287c3a27a89d712
      token: tttt123sdg
      encodingAESKey: <encodingAESKey>
  redis:
    # 默认缓存时间 2小时 2*60*60=7200 秒
    defaultTtl: 7200
