import Head from 'next/head'
import Image from 'next/image'
import Layout from "../components/layout";
import {Col, Row, Button, Space, DatePicker, Typography} from 'antd';
import {ArrowRightOutlined, CiCircleFilled} from '@ant-design/icons';
import styles from '../styles/Home.module.css'

const {Title} = Typography;

const Home = () => {
    const onChange = () => {
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>renfeid</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.banner_wrapper}>
                <div className={styles.banner}>
                    <Row>
                        <Col span={15} className={styles.banner_col}>
                            <div className={styles.banner_img_wrapper}>
                                <img
                                    className={styles.banner_img}
                                    src={"https://cdn.renfei.net/upload/2022/2af9436a41c945e58b98d5ac09835179.webp?x-oss-process=style/992.558"}
                                    alt={""}/>
                            </div>
                        </Col>
                        <Col span={9} className={styles.banner_col}>
                            <div className={styles.banner_content_wrapper}>
                                <a style={{display: 'block'}}>
                                    <Title level={2}
                                           className={styles.banner_content_h2}>关于我在极狐GitLab造机器人这件事儿我觉得很酷</Title>
                                    <p className={styles.banner_content_p}>我在参与极狐GitLab创作营 JIHULAB
                                        101活动的时候，发现极狐GitLab官方启用了一个机器人，会在issue哪里进行服务，我就突发奇想，很多地方都有自动回复的客服机器人，那在极狐GitLab能不能造个机器人玩？</p>
                                    <span className={styles.banner_content_icon}><ArrowRightOutlined/></span>
                                </a>
                            </div>
                        </Col>
                    </Row>
                </div>
            </div>
            <main className={styles.main}>
                <section className={"renfeid-content"}>
                    <div className={styles.posts_top5}>
                        <Title level={3}>任霏博客</Title>
                        <Row>
                            <Col span={12}>
                                sdf
                            </Col>
                            <Col span={12}>
                                sdf
                            </Col>
                        </Row>
                    </div>
                </section>

                <h1 className={styles.title}>
                    Welcome to <a href="https://www.renfei.net">renfeid !</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>

                <Space direction="vertical">
                    <Button type="primary">Primary Button</Button>
                    <Button type="ghost">Ghost Button</Button>
                    <DatePicker onChange={onChange}/>
                    <CiCircleFilled/>
                </Space>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

Home.getLayout = (page: any) => {
    return (
        <Layout>
            {page}
        </Layout>
    )
}

export default Home
